parameters = {
    "path_source_img":"/home/lionel/theo/post_doc/whole_bird",
    "path_source_split":"/home/lionel/theo/post_doc/project/saved_split_limit:1000.pkl",
    "path_source_csv":"/home/lionel/theo/post_doc/final_table2.csv",
    "name":"Dino_binary_sampling_1000",
    "env_selected" : 13,
    "img_size":224,
    "model" : "dino",
    "train_batch_size" : 10,
    "valid_batch_size" : 20,
    "loss" : "BCEWithLogitsLoss",
    "optimizer" : "Adam",
    "lr": 1e-7,
    "weight_decay":1e-4,
    "epochs": 5,
    "device":"cuda",
    "opt":"adam",
    "warmup_epochs":1,
    "image_limitation" : 1000,
}